import { readFile } from 'node:fs/promises';
import { createPrivateKey } from 'node:crypto';
import { HttpAgent } from '@icp-sdk/core/agent';
import { Ed25519KeyIdentity } from '@icp-sdk/core/identity';
import { Secp256k1KeyIdentity } from '@icp-sdk/core/identity/secp256k1';
import type { Config } from './config.js';

/**
 * Load the PEM file and create an authenticated ICP HttpAgent.
 *
 * PEM file → identity → HttpAgent
 *      │         │           │
 *      │         │           └─ Connects to ic0.app (mainnet) or ICP_NODE_URL
 *      │         ├─ Ed25519KeyIdentity  (dfx default since v0.14, PKCS8 PEM)
 *      │         └─ Secp256k1KeyIdentity (icp-cli default, older dfx, SEC1/PKCS8 EC PEM)
 *      └─ Generated by:
 *           dfx:      dfx identity export <name> > identity.pem
 *           icp-cli:  icp-cli new-identity <name>  (stored at ~/.config/dfx/identity/<name>/identity.pem)
 *
 * Key detection: parse PEM via Node.js crypto → JWK → check kty/crv.
 *   kty=OKP  crv=Ed25519   → Ed25519KeyIdentity.fromSecretKey()
 *   kty=EC   crv=secp256k1 → Secp256k1KeyIdentity.fromPem()
 *
 * fetchRootKey() is called eagerly for non-mainnet so the first tool
 * call doesn't pay the latency cost and errors surface at startup.
 */
export async function createAgent(config: Config): Promise<HttpAgent> {
  let pemContent: string;
  try {
    pemContent = await readFile(config.identityPemPath, 'utf-8');
  } catch {
    throw new Error(
      `PEM file not found at "${config.identityPemPath}". ` +
        `Export your identity with:\n` +
        `  dfx:      dfx identity export <name> > identity.pem\n` +
        `  icp-cli:  identity PEM is at ~/.config/dfx/identity/<name>/identity.pem`,
    );
  }

  let identity: Ed25519KeyIdentity | Secp256k1KeyIdentity;
  try {
    identity = identityFromPem(pemContent);
  } catch (err) {
    throw new Error(
      `Could not parse PEM in "${config.identityPemPath}": ` +
        `${err instanceof Error ? err.message : String(err)}. ` +
        `Supported formats: PKCS8 Ed25519 (dfx default), SEC1/PKCS8 secp256k1 (icp-cli / older dfx).`,
    );
  }

  const host = config.icpNodeUrl ?? 'https://ic0.app';
  const agent = HttpAgent.createSync({ identity, host });

  if (config.icpNetwork !== 'mainnet') {
    try {
      await agent.fetchRootKey();
    } catch (err) {
      throw new Error(
        `Failed to fetch ICP root key from ${host}. ` +
          `Is the ICP node reachable? Error: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  return agent;
}

/**
 * Parse a PEM file exported by dfx or icp-cli into an ICP identity.
 *
 * Supports two formats:
 *   - PKCS8 Ed25519 (dfx default since v0.14, kty=OKP crv=Ed25519)
 *   - SEC1/PKCS8 secp256k1 (icp-cli default, older dfx, kty=EC crv=secp256k1)
 */
function identityFromPem(pem: string): Ed25519KeyIdentity | Secp256k1KeyIdentity {
  const keyObject = createPrivateKey(pem);
  const jwk = keyObject.export({ format: 'jwk' }) as {
    kty: string;
    crv?: string;
    d: string;
  };

  if (jwk.kty === 'OKP' && jwk.crv === 'Ed25519') {
    // dfx default: PKCS8 Ed25519
    const secretBytes = Buffer.from(jwk.d, 'base64url');
    return Ed25519KeyIdentity.fromSecretKey(
      new Uint8Array(secretBytes.buffer, secretBytes.byteOffset, secretBytes.byteLength),
    );
  }

  if (jwk.kty === 'EC' && jwk.crv === 'secp256k1') {
    // icp-cli / older dfx: secp256k1 PEM
    return Secp256k1KeyIdentity.fromPem(pem);
  }

  throw new Error(
    `Unsupported key type: kty=${jwk.kty} crv=${jwk.crv ?? 'n/a'}. ` +
      `Expected Ed25519 (PKCS8 from dfx) or secp256k1 (from icp-cli / older dfx).`,
  );
}
