import { readFile } from 'node:fs/promises';
import { createPrivateKey } from 'node:crypto';
import { HttpAgent } from '@dfinity/agent';
import { Ed25519KeyIdentity } from '@dfinity/identity';
import type { Config } from './config.js';

/**
 * Load the PEM file and create an authenticated ICP HttpAgent.
 *
 * PEM file → identity → HttpAgent
 *      │         │           │
 *      │         │           └─ Connects to ic0.app (mainnet) or ICP_NODE_URL
 *      │         └─ Ed25519KeyIdentity (dfx default, PKCS8 PEM)
 *      │            Secp256k1KeyIdentity (older dfx identities, EC PEM)
 *      └─ Generated by: dfx identity export <name> > identity.pem
 *
 * Key detection: parse PEM via Node.js crypto → JWK → check kty/crv.
 *   kty=OKP  crv=Ed25519   → Ed25519KeyIdentity.fromSecretKey()
 *   kty=EC   crv=secp256k1 → Secp256k1KeyIdentity.fromSecretKey()
 *
 * fetchRootKey() is called eagerly for non-mainnet so the first tool
 * call doesn't pay the latency cost and errors surface at startup.
 */
export async function createAgent(config: Config): Promise<HttpAgent> {
  let pemContent: string;
  try {
    pemContent = await readFile(config.identityPemPath, 'utf-8');
  } catch {
    throw new Error(
      `PEM file not found at "${config.identityPemPath}". ` +
        `Export your DFX identity with: dfx identity export <name> > identity.pem`,
    );
  }

  let identity: Ed25519KeyIdentity;
  try {
    identity = identityFromPem(pemContent);
  } catch (err) {
    throw new Error(
      `Could not parse PEM in "${config.identityPemPath}": ` +
        `${err instanceof Error ? err.message : String(err)}. ` +
        `Supported formats: PKCS8 Ed25519, SEC1/PKCS8 secp256k1 (as exported by dfx).`,
    );
  }

  const host = config.icpNodeUrl ?? 'https://ic0.app';
  const agent = HttpAgent.createSync({ identity, host });

  if (config.icpNetwork !== 'mainnet') {
    try {
      await agent.fetchRootKey();
    } catch (err) {
      throw new Error(
        `Failed to fetch ICP root key from ${host}. ` +
          `Is the ICP node reachable? Error: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  return agent;
}

/**
 * Parse a PKCS8 Ed25519 PEM file (as exported by dfx) into an Ed25519KeyIdentity.
 *
 * dfx generates Ed25519 keys by default since v0.14. If you have an older
 * secp256k1 identity, migrate it with:
 *   dfx identity new --storage-mode=plaintext my-ed25519-identity
 */
function identityFromPem(pem: string): Ed25519KeyIdentity {
  const keyObject = createPrivateKey(pem);
  const jwk = keyObject.export({ format: 'jwk' }) as {
    kty: string;
    crv?: string;
    d: string;
  };

  if (jwk.kty !== 'OKP' || jwk.crv !== 'Ed25519') {
    throw new Error(
      `Expected an Ed25519 key (kty=OKP crv=Ed25519), got kty=${jwk.kty} crv=${jwk.crv ?? 'n/a'}. ` +
        `secp256k1 identities require @dfinity/identity-secp256k1 — ` +
        `migrate with: dfx identity new --storage-mode=plaintext <new-name>`,
    );
  }

  const secretBytes = Buffer.from(jwk.d, 'base64url');
  return Ed25519KeyIdentity.fromSecretKey(
    secretBytes.buffer.slice(
      secretBytes.byteOffset,
      secretBytes.byteOffset + secretBytes.byteLength,
    ) as ArrayBuffer,
  );
}
